name: CI
on:
  push:
    branches:
      - main
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    strategy:
      matrix:
        platform:
          - name: Linux
            target: ubuntu-latest
            executable: gameone
          - name: Windows
            target: windows-latest
            executable: gameone.exe
          - name: Mac
            target: macos-latest
            executable: gameone
        profile:
          - name: Debug
            directory: debug
            flag: ""
          - name: Release
            directory: release
            flag: "--release"

    name: ${{ matrix.platform.name }} ${{ matrix.profile.name }}
    runs-on: ${{ matrix.platform.target }}
    steps:
      - name: Install linux packages
        if: runner.os == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev
          sudo apt-get install libudev-dev

      - uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.platform.name }}-${{ matrix.profile.name }}

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Build
        run: cargo build ${{ matrix.profile.flag }}

      - name: Lint
        run: cargo clippy ${{ matrix.profile.flag }}

      - name: Run tests
        run: cargo test ${{ matrix.profile.flag }}

      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform.name }}-${{ matrix.profile.name }}
          path: target/${{ matrix.profile.directory }}/${{ matrix.platform.executable }}
