name: CI
on: push
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macOS-latest]
        profile: ["", --release]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install linux packages
        if: runner.os == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev
          sudo apt-get install libudev-dev

      - uses: actions/checkout@v2

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Build
        run: cargo build ${{ matrix.profile }}

      - name: Lint
        run: cargo clippy ${{ matrix.profile }}

      - name: Run tests
        run: cargo test ${{ matrix.profile }}
